export enum Voivodeships {
    dolnoslaskie = 'Dolnośląskie',
    kujawskoPomorskie = 'Kujawsko-pomorskie',
    lubelskie = 'Lubelskie',
    lubuskie = 'Lubuskie',
    lodzkie = 'Łódzkie',
    malopolskie = 'Małopolskie',
    mazowieckie = 'Mazowieckie',
    opolskie = 'Opolskie',
    podkarpackie = 'Podkarpackie',
    podlaskie = 'Podlaskie',
    pomorskie = 'Pomorskie',
    slaskie = 'Śląskie',
    swietokrzyskie = 'Świętokrzyskie',
    warminskoMazurskie = 'Warmińsko-mazurskie',
    wielkopolskie = 'Wielkopolskie',
    zachodniopomorskie = 'Zachodniopomorskie',
}
