export const environment = {
    apiUrl: {
        baseUrl: 'http://localhost:8080/api/v1',
        allOffers: '/offers',
        offerDetails: '/details',
        register: '/authentication/register',
        login: '/authentication/login',
        refresh: '/authentication/refresh',
        image: '/image',
        createOffer: '/offers/create',
        buy: '/buy',
        createCompany: '/company/create',
        userOffers: '/user-offers',
        organizerOffers: '/organizer-offers',

        get registerUrl() {return `${this.baseUrl}${this.register}`;},
        get loginUrl() {return `${this.baseUrl}${this.login}`;},
        get refreshUrl() {return `${this.baseUrl}${this.refresh}`;},
        get allOffersUrl() {return `${this.baseUrl}${this.allOffers}`;},
        get createOfferUrl(){return `${this.baseUrl}${this.createOffer}`;},
        get createCompanyUrl(){return `${this.baseUrl}${this.createCompany}`;},
        get userOffersUrl(){return `${this.baseUrl}${this.allOffers}${this.userOffers}`;},
        get organizerOffersUrl(){return `${this.baseUrl}${this.allOffers}${this.organizerOffers}`;},
        offerDetailsUrl(flightId: number) {return `${this.baseUrl}${this.allOffers}/${flightId}${this.offerDetails}`;},
        organizerOfferDetailsUrl(flightId: number) {return `${this.baseUrl}${this.allOffers}${this.organizerOffers}/${flightId}${this.offerDetails}`;},
        offerImageUrl(imageFilename: string){return `${this.baseUrl}${this.image}/${imageFilename}`;},
        buyOfferUrl(flightId: number) {return `${this.baseUrl}${this.allOffers}/${flightId}${this.buy}`;},
    },
    appUrl: {
        offersList: '/offers',
        organizerOffersList: '/organizer-offers',
        account: '/account',
        generateOfferDetailsUrl(flightId: number){return `/${this.offersList}/${flightId}`},
        generateOrganizerOfferDetailsUrl(flightId: number){return `/${this.account}${this.organizerOffersList}/${flightId}`},
    },
};
